### ISSUE TITLE
Should be able to import 'Web3Provider' type.

### ISSUE THREAD

**Issue by dipapazacharias** [web3-wallet/web3-wallet#27]
My Problem:
I want to pass the returned value of `useProvider()` hook as a parameter to a typescript function. But I cannot import its corresponding type (`Web3Provider`) from `@web3-wallet/react.`

Desired solution:
A simple type export would suffice. All types returned from currentWallet hooks shoud be exported, in general. It would be very helpful, and it is very simple to implement.

Note: 
I tried 

`import type { Wallet } from '@web3-wallet/react';
type Web3Provider = ReturnType<Wallet['useProvider']>`

but then I get `Property 'provider' does not exist on type 'BaseProvider'.` typescript warning, while provider property is there

**Comment by logan272** [comment]
hey @dipapazacharias, thanks for your feedbacks.

1. The Web3Provider is retrieve from the wallet asynchronously. The `useProvider` hook returns `Web3Provider | undefined` not Web3Provider. You function should probably also take `Web3Provider | undefined` as it's input not just Web3Provider. 
2. Since you can use `useProvider` in any other hook, you may not need to pass Web3Provider as an parameter to your hooks. Instead, you can use `useProvider` directly in your hooks. 
3. The Web3Provider and BaseProvider are both imported directly from the `@ethersproject/providers` package.
